Bitcoin-com/developer.bitcoin.com

- html/pages/mastering-bitcoin-cash/what-is-bitcoin-cash.html
Changed "Joe to scan the barcode" to "Joe scans the barcode"
> Fixed spelling/grammar mistake

- html/pages/bitbox/docs/getting-started.html
Adds a call-to-action to the "New" page on the "Getting Started" page. Also includes a code snippet to import BITBOX if users do not want to use the scaffolding tool.
> Adds usage instructions

- gatsby-restart/src/data/docs/bitbox/getting-started.md
- gatsby-restart/src/data/docs/bitbox/mnemonic.md
- gatsby-restart/src/data/docs/wormhole/configuration.md
- gatsby-restart/src/data/docs/wormhole/data-retrieval.md
- gatsby-restart/src/data/docs/wormhole/payload-creation.md
- gatsby-restart/src/data/docs/wormhole/raw-transactions.md
- gatsby-restart/src/data/docs/wormhole/transaction.md
- gatsby-restart/src/data/docs/wormhole/wallet.md
Refactoring to `await` syntax and format docs.
> Use await syntax

- html/pages/develop.html
Simple copy change to buttons from a request in office
> Revised disabled button copy to coming soon

- gatsby-restart/src/data/docs/bitbox/address.md
- gatsby-restart/src/data/docs/wormhole/erc20.md
> ERC20 docs.

- src/data/docs/bitbox/getting-started.md
- src/data/insights/scale.cash.md
- src/data/tutorials/address-utxo.md
- src/data/tutorials/bitbox-cli.md
- src/data/tutorials/bitbox-scaffolds.md
- src/data/tutorials/bitbox-typescript-support.md
- src/data/tutorials/extended-public-keys.md
- src/data/tutorials/getting-started.md
- src/data/tutorials/sign-and-verify.md
- src/data/tutorials/utilities-part-1.md
- src/pages/about.js
- src/pages/bitbox.js
- src/pages/index.js
- src/pages/wormhole.js
* Update bitbox-cli to bitbox-sdk
* Update BITBOXCli to BITBOXSDK
> bitbox-sdk

- README.md
- src/data/docs/wormhole/console.md
- src/data/docs/wormhole/data-retrieval.md
- src/data/docs/wormhole/new.md
- src/data/tutorials/address-utxo.md
- src/data/tutorials/bitbox-typescript-support.md
- src/data/tutorials/getting-started.md
> Merge stage -> master

- src/data/docs/bitbox/address.md
- src/data/docs/wormhole/payload-creation.md
> Address.isHash160

- src/components/ShareFooter.js
* Manually load and clean-up optinmonster scripts
* Trigger the OM form mount manually after first mount
> Optin Monster form fix

- src/components/NavBar.js
* Fixing navbar being below some elements
> Bug - Navbar below OM form

- src/data/docs/wormhole/console.md
- src/data/faucets/bch.md
- src/pages/develop.js
- src/pages/faucets.js
- src/pages/faucets/bch.js
- src/pages/faucets/whc.js
- src/templates/faucetPage.js
This is a functional version of the BCH and WHC faucets.
Note: The front end currently points to my personal back end. I'll remove this note once I get the bitcoin.com back end setup and it's safe to change the URL.
There are some minor improvements I'd like to add - like current balance of each faucet in BCH and WHC, that way it's easy for Bitcoin.com developers to maintain them. The WHC faucet needs to be periodically recharged, but the BCH faucet should be automatically refilled by the mining team.
> Faucets Ready

- src/data/docs/wormhole/data-retrieval.md
- src/data/docs/wormhole/payload-creation.md
* ERC721AddressTokens
* ERC721PropertyDestroyTokens
* ERC721PropertyNews
* ERC721TokenNews
* ownerOfERC721Token
* issueERC721Property
* issueERC721Token
* transferERC721Token
* destroyERC721Token
> ERC721 docs

- package.json
- src/components/bch-faucet.js
- src/components/whc-faucet.js
- yarn.lock
* fetch-polyfill, fixes the build
> Isomorphic fetch polyfill

- src/atoms/H1.js
- src/atoms/H2.js
- src/atoms/H3.js
- src/atoms/H4.js
> Bug - import case fix

- src/pages/index.js
* Fixing wrapping of homescreen buttons on mobile devices
> Bug - Fixing button wrapping on homepage

- src/pages/bitbox.js
- src/pages/gui.js
- src/pages/rest.js
- src/pages/slp.js
- src/pages/wormhole.js
* Minimal change to reduce whitespace and tighten the SDK preview pages
* Slightly smaller fonts
* All entries are full rows, allows more code to be viewed at a time.
> Improvement - Tighter SDK example pages

- src/data/docs/rest/dataretrieval.md
> Data retrieval docs.

- README.md
- gatsby-config.js
- gatsby-node.js
- package.json
- src/components/Hero.js
- src/components/NavBar.js
- src/pages/about.js
- src/pages/badger.js
- src/pages/bitbox.js
- src/pages/develop.js
- src/pages/faucets.js
- src/pages/faucets/bch.js
- src/pages/faucets/whc.js
- src/pages/gui.js
- src/pages/index.js
- src/pages/insights.js
- src/pages/learn.js
- src/pages/mastering-bitcoin-cash.js
- src/pages/rest.js
- src/pages/slp.js
- src/pages/tutorials.js
- src/pages/wormhole.js
- src/styles/palette.js
- src/styles/themes.js
* `/badger` basic page - content to be added now
* `/develop` added card for `/badger`
* `/` Added link in header to `/badger`
* ALL hero images now duotone processed + scale up after initial load
* Index images also scale up
* Misc minor cleanup
> Badger Non doc pages + Image up-sizing on all the pages

- src/data/docs/badger/badger-button.md
- src/data/docs/badger/cash-id.md
- src/data/docs/badger/send-slp-token.md
- src/data/docs/badger/send-wormhole-token.md
Specific wormhole & slp docs
Badger Button link
> Badger docs updates

- src/data/docs/slp/console.md
> Hotfix - typo

- gatsby-config.js
- package-lock.json
- src/pages/about.js
- src/pages/badger.js
- src/pages/bitbox.js
- src/pages/develop.js
- src/pages/faucets.js
- src/pages/faucets/bch.js
- src/pages/faucets/whc.js
- src/pages/gui.js
- src/pages/insights.js
- src/pages/learn.js
- src/pages/mastering-bitcoin-cash.js
- src/pages/rest.js
- src/pages/slp.js
- src/pages/tutorials.js
- src/pages/wormhole.js
- Update page title to "Bitcoin.com Developer Portal"
- Uses graphql on all pages to get title from gatsby-config
> Update page titles

- src/data/docs/badger/badger-button.md
> Badger token button

- package-lock.json
- src/data/docs/bitbox/address.md
- src/data/docs/bitbox/block.md
- src/data/docs/bitbox/blockchain.md
- src/data/docs/bitbox/rawtransactions.md
- src/data/docs/bitbox/util.md
Contains the documentation updates for BITBOX to reflect code changes to take advantage of the new rest v2 endpoints.
> BITBOX doc changes for rest v2

- src/data/docs/rest/rawtransactions.md
> Update rest docs

- package-lock.json
- src/data/docs/bitbox/rawtransactions.md
- src/data/docs/bitbox/transaction.md
Updating BITBOX docs for sendRawTransaction and Transaction.details endpoints
> Updating BITBOX docs for sendRawTransaction and Transaction.details endpoints

- package.json
- src/data/docs/rest/address.md
- src/data/docs/rest/slp.md
- src/data/docs/slp/tokentype1.md
* address/fromXPub
* slp/list return values
> Updates to REST docs

- package.json
- yarn.lock
* Explicitly include React libraries
> Bug - explicit react versions

- README.md
- src/data/docs/badger/badger-components-react.md
* Documentation  for React components and OP_RETURN
> Documentation - Updating badger react docs with OP_RETURN examples

- src/pages/index.js
- src/pages/learn.js
- src/pages/tutorials.js
* Fixing the typos reported in #182 
* fixes #182
> Bug - Fixing some reported typos and phrasing

- package.json
- yarn.lock
* Update badger-components-react to version with latest hotfix
> Badger-react hotfix update

- package.json
- src/data/docs/badger/badger-components-react.md
- src/utils/markdown-helpers.js
- yarn.lock
* badger-components-react 0.3.0 documentation update
* Using 0.3.0 in examples
* Minor package version updates
* fixes #203
> Docs - badger-components-react 0.3.0

- package.json
- src/data/docs/slp/tokentype1.md
**DO NOTE MERGE**
This is dependent on https://github.com/Bitcoin-com/slp-sdk/pull/24
> SLP.TokenType1.burn docs

- src/data/docs/bitbox/address.md
- src/data/docs/bitbox/ecpair.md
- src/data/docs/bitbox/transactionBuilder.md
Added more description and links to documentation. 
Added more description in the returned object because a lot of it is implicit and hard to know ahead of time without trying it.
Also fixed small errors in the examples.
We need as much info as possible because for a first-timer, this is really hard to get into with the sparse description we currently have.
> Kralux patch 2

- src/data/docs/badger/badger-components-react.md
* Fixing some doc errors
* fixes #231
> Typos - doc badger react fixes

- package.json
- src/data/docs/rest/address.md
- src/data/docs/rest/slp.md
* SLP REST custodial endpoints
* REST Address endpoints
> Updates to docs.

- package.json
- src/data/docs/bitbox/script.md
* encodeNumber 
* decodeNumber
> Script class

- src/data/docs/slp/js/util.md
This PR includes several updates to the slp-sdk Util class documentation:
- Renames the `Utils` class to `Util` to bring it into alignment with BITBOX documentation.
- Adds documentation for the `decodeOpReturn(txid)` method.
- Adds documentation for the `isTokenUtxo(utxos)` method.
> slp-sdk Util Class Documentation

- src/data/docs/cashscript/cashc.md
- src/data/docs/cashscript/getting-started.md
- src/data/docs/cashscript/language.md
- src/data/docs/cashscript/sdk.md
- Add docs on transaction errors
- Add docs for browser usage
- Update docs for cashc CLI
- Add docs for `OutputNullData`
- Add docs for `minChange`
- Cleanup
> CashScript updates
